SSR & Route provider support
pankod/refine pull request #1107
Opened 2021-09-20 06:49 UTC by mhrrmk

Test me! 'MASTER'
[Link to SSR-SUPPORT](https://ssr-sup-refine.pankod.com)

Test documentation! 'MASTER'
[Link to SSR-SUPPORT](https://ssr-sup-doc-refine.pankod.com)

2021-09-28 07:00 UTC, mhrrmk commented on packages/core/src/components/antd/datePicker.tsx
> +// import "antd/es/date-picker/style/index.css";
disabled import

2021-09-28 07:00 UTC, mhrrmk commented on packages/core/src/components/antd/calendar.tsx
> +// import "antd/es/calendar/style/index.css";
disabled import

2021-09-28 07:02 UTC, mhrrmk commented on packages/core/src/index.tsx
> +// import "node_modules/antd/dist/antd.css";
disabled import

2021-09-28 07:03 UTC, mhrrmk commented on packages/core/src/index.tsx
> +// export * from "react-query";
disabled export

2021-10-05 14:16 UTC, omeraplak requested changes

2021-10-05 14:16 UTC, omeraplak commented on packages/core/src/hooks/auth/useLogin/index.ts
> +                replace(search.substring(4) ?? "/");
ups this looks buggy :)

2021-10-06 08:03 UTC, merged