Rbac Provider
pankod/refine pull request #1229
Opened 2021-11-11 09:54 UTC by salihozdemir

**Closing issues**

closes #743

2021-11-15 07:01 UTC, omeraplak commented
- [ ] accessControl Provider
- [ ] CanAccess component & useCan hook
- [ ] nextjs-router & react-router integration
- [ ] CRUD components
- [ ] integrate useCan hook
- [ ] sider
- [ ] casbin example
- [ ] unit tests
- [ ] Doc
- [ ] Guide

2021-11-22 15:51 UTC, omeraplak requested changes

2021-11-22 15:51 UTC, omeraplak commented on documentation/docs/api-references/providers/accessControl-provider.md
> +            },
```suggestion
            can: async ({ resource, action, params }) => {
                if(resource === "posts" && action === "edit")
                {
                    return Promise.resolve(false);
                }

                return Promise.resolve(true);
            },
```

2021-11-22 15:51 UTC, omeraplak commented on documentation/docs/api-references/providers/accessControl-provider.md
> +);
```suggestion
const { data } = useCan({
    resource: "resource-you-ask-for-access",
    action: "action-type-on-resource",
    params: { foo: "optional-params" } },
);
```

2021-11-22 15:51 UTC, omeraplak commented on documentation/docs/api-references/providers/accessControl-provider.md
> +`<CanAccess/>` is a wrapper component that uses `useCan` to check for access control. It takes the parameters that `can` method takes and also a `fallback`. It renders its children if the access cont
```suggestion

### `<CanAccess />`

`<CanAccess />` is a wrapper component that uses `useCan` to check for access control. It takes the parameters that `can` method takes and also a `fallback`. It renders its children if the access control returns true and if access control returns false renders `fallback` if provided.
```

2021-11-22 15:51 UTC, omeraplak commented on documentation/docs/api-references/providers/accessControl-provider.md
> +    <YourComponent>
```suggestion
    <YourComponent />
```

2021-11-22 15:51 UTC, omeraplak commented on documentation/docs/api-references/providers/accessControl-provider.md
> +    fallback={<CustomFallback/>}
```suggestion
    resource="posts"
    action="edit"
    params={{ id: 1 }}
    fallback={<CustomFallback/>}
```

2021-11-24 15:18 UTC, omeraplak requested changes

2021-11-24 15:18 UTC, omeraplak commented on documentation/docs/guides-and-concepts/access-control.md
> +The app will have three resources: **posts**, **users** and **categories** with crud pages(list, create, edit and show)
```suggestion
The app will have three resources: **posts**, **users** and **categories** with CRUD pages(list, create, edit and show)
```

2021-11-24 15:18 UTC, omeraplak commented on documentation/docs/guides-and-concepts/access-control.md
> +We will be using **casbin** in this guide for users with different roles who have different access rights for parts of the app.
```suggestion
We will be using **[Casbin](https://casbin.org/)** in this guide for users with different roles who have different access rights for parts of the app.
```

2021-11-24 15:18 UTC, omeraplak commented on documentation/docs/guides-and-concepts/access-control.md
> +Access control is a broad topic where there are lots of advanced solutions that provide different set of features. **refine** is deliberately agnostic for its own API to be able to integrate differen
```suggestion
Access control is a broad topic where there are lots of advanced solutions that provide different set of features. **refine** is deliberately agnostic for its own API to be able to integrate different solutions(RBAC, ABAC, ACL, IP, LDAP, etc...). `can` method would be the entry point for those solutions.
```

2021-11-24 15:18 UTC, omeraplak commented on documentation/docs/guides-and-concepts/access-control.md
> +We need to install casbin.
```suggestion
We need to install Casbin.
```

2021-11-24 15:18 UTC, omeraplak commented on documentation/docs/guides-and-concepts/access-control.md
> +The way **casbin** works is that access rights are checked according to policies that are defined based on a model. [You can find further information about how models and policies work here](https://
```suggestion
The way **[Casbin](https://casbin.org/)** works is that access rights are checked according to policies that are defined based on a model. [You can find further information about how models and policies work here](https://casbin.org/docs/en/how-it-works).
```

2021-11-25 06:09 UTC, omeraplak requested changes

2021-11-25 06:09 UTC, omeraplak commented on documentation/docs/guides-and-concepts/access-control.md
> +                    });
```suggestion
                    const enforcer = await newEnforcer(model, adapter);
                    const can = await enforcer.enforce("editor", resource, action);

                    return Promise.resolve({
                        can,
                    });
```

2021-11-25 11:44 UTC, omeraplak requested changes

2021-11-25 11:44 UTC, omeraplak commented on documentation/docs/api-references/providers/accessControl-provider.md
> +- clone (e.g. `/posts/create/1`): `{resource: "posts", action: "create", params: {id :1}}`
```suggestion
- clone (e.g. `/posts/clone/1`): `{resource: "posts", action: "create", params: {id :1}}`
```

2021-11-25 11:47 UTC, omeraplak requested changes

2021-11-25 11:47 UTC, omeraplak commented on documentation/docs/api-references/providers/accessControl-provider.md
> +For example if your app has resource `posts` it will be checked with `{resource: "posts", action: "list"}`
```suggestion
For example if your app has resource `posts` it will be checked with `{ resource: "posts", action: "list" }`
```

2021-11-25 11:47 UTC, omeraplak commented on documentation/docs/api-references/providers/accessControl-provider.md
> +- create (e.g. `/posts/create`): `{resource: "posts", action: "create"}`
```suggestion
- list (e.g. `/posts`): `{ resource: "posts", action: "list" }`
- create (e.g. `/posts/create`): `{ resource: "posts", action: "create" }`
```

2021-11-25 11:47 UTC, omeraplak commented on documentation/docs/api-references/providers/accessControl-provider.md
> +- show (e.g. `/posts/show/1`): `{resource: "posts", action: "show", params: {id :1}}`
```suggestion
- edit (e.g. `/posts/edit/1`): `{ resource: "posts", action: "edit", params: {id :1} }`
- show (e.g. `/posts/show/1`): `{ resource: "posts", action: "show", params: {id :1} }`
```

2021-11-25 11:47 UTC, omeraplak commented on documentation/docs/api-references/providers/accessControl-provider.md
> +- [**show**](/api-references/components/buttons/show.md): `{resource: "posts, action: "show", params: { id: 1 }}`
```suggestion
- [**list**](/api-references/components/buttons/list.md): `{ resource: "posts, action: "list" }`
- [**create**](/api-references/components/buttons/create.md): `{ resource: "posts, action: "create" }`
- [**clone**](/api-references/components/buttons/clone.md): `{ resource: "posts, action: "create", params: { id: 1 } }`
- [**edit**](/api-references/components/buttons/edit.md): `{ resource: "posts, action: "edit", params: { id: 1 } }`
- [**delete**](/api-references/components/buttons/delete.md): `{ resource: "posts, action: "delete", params: { id: 1 } }`
- [**show**](/api-references/components/buttons/show.md): `{ resource: "posts, action: "show", params: { id: 1 } }`
```

2021-11-25 11:47 UTC, omeraplak commented on documentation/docs/api-references/providers/accessControl-provider.md
> +These buttons will be disabled if access control returns `false`
```suggestion
These buttons will be disabled if access control returns `{ can: false }`
```

2021-11-25 11:49 UTC, omeraplak requested changes

2021-11-25 11:49 UTC, omeraplak commented on documentation/docs/api-references/providers/accessControl-provider.md
> +[ReactRouter]: https://www.npmjs.com/package/@pankod/refine-react-router
```suggestion
[ReactRouter]: https://www.npmjs.com/package/@pankod/refine-react-router
[ReactLocation]: https://www.npmjs.com/package/@pankod/refine-react-location
```

2021-11-25 11:49 UTC, omeraplak commented on documentation/docs/api-references/providers/accessControl-provider.md
> +[`@pankod/refine-nextjs-router`][NextjsRouter] and [`@pankod/refine-react-router`][ReactRouter] packages integrate access control for crud pages at `[resource]/[action]` routes.
```suggestion
[`@pankod/refine-nextjs-router`][NextjsRouter], [`@pankod/refine-react-router`][ReactRouter], and [`@pankod/refine-react-location`][ReactLocation] packages integrate access control for CRUD pages at `[resource]/[action]` routes.
```

2021-11-26 08:06 UTC, miyavsu-limited commented on documentation/docs/guides-and-concepts/access-control.md
> +                    return Promise.resolve({ can });
```suggestion
                    return { can };
```

2021-11-26 08:07 UTC, miyavsu-limited commented on documentation/docs/guides-and-concepts/access-control.md
> +[You can refer to codesandbox to how they are implemented](#live-codesandbox-example)
```suggestion
[You can refer to codesandbox to see how they are implemented](#live-codesandbox-example)
```

2021-11-26 08:11 UTC, miyavsu-limited commented on documentation/docs/guides-and-concepts/access-control.md
> +                    });
```suggestion
                    return {
                        can,
                    };
```

2021-11-26 08:12 UTC, miyavsu-limited commented on documentation/docs/guides-and-concepts/access-control.md
> +                        return Promise.resolve({ can });
```suggestion
                        return { can };
```

2021-11-26 08:12 UTC, miyavsu-limited commented on documentation/docs/guides-and-concepts/access-control.md
> +                    return Promise.resolve({ can });
```suggestion
                    return { can };
```

2021-11-26 08:13 UTC, miyavsu-limited commented
Wrapping async functions return values in `Promise.resolve` is unnecessary, removing all of them would be a good idea

2021-11-26 09:44 UTC, omeraplak requested changes

2021-11-26 09:44 UTC, omeraplak commented on documentation/versioned_docs/version-2.xx.xx/getting-started/overview.md
> +☑️ Support for more UI frameworks (MaterialUI, Chakra, Spectrum etc.)
```suggestion
```

2021-11-26 13:11 UTC, merged