Add realtime features
pankod/refine pull request #1255
Opened 2021-11-17 11:47 UTC by miyavsu-limited

closes #1254

2021-12-02 09:58 UTC, salihozdemir commented on examples/dataProvider/supabase/src/pages/posts/edit.tsx
> +                        </Space>
There is no need to use `<Space>` component here, we may not use it

2021-12-02 09:58 UTC, salihozdemir commented on examples/dataProvider/supabase/src/pages/posts/show.tsx
> +                        </Space>
We may not use `<Space>` here

2021-12-02 09:58 UTC, salihozdemir commented on packages/core/src/hooks/data/useCreate.ts
> +                    date: new Date(),
Now, we may use usePublish hook in here

2021-12-07 07:58 UTC, yildirayunlu commented on documentation/docs/guides-and-concepts/real-time.md
> +            //highlight-end //highlight-start
```suggestion
            //highlight-end 
            //highlight-start
```
![image](https://user-images.githubusercontent.com/3484713/144989195-68270563-c366-493b-bfa2-47522fee1cca.png)

2021-12-07 09:11 UTC, omeraplak requested changes

2021-12-07 09:11 UTC, omeraplak commented on documentation/docs/api-references/hooks/live/usePublish.md
> +    type: "updated",
```suggestion
    type: "updated",
```
```suggestion
    type: "custom-event-name",
```

2021-12-07 09:11 UTC, omeraplak commented on documentation/docs/api-references/hooks/live/usePublish.md
> +    },
```suggestion
    payload: {
        "custom-property": "custom-property-value",
    },
```

2021-12-07 09:11 UTC, omeraplak commented on documentation/docs/api-references/hooks/live/usePublish.md
> +    channel: `resources/${resource}`,
```suggestion
    channel: "custom-channel-name",
```

2021-12-07 09:11 UTC, omeraplak commented on documentation/docs/api-references/hooks/live/usePublish.md
> +If you need to publish an events **refine** provides the `usePublish` hook for it, It returns the `publish` method from [`liveProvider`](/api-references/providers/live-provider.md) under the hood.
```suggestion
If you need to custom publish an events **refine** provides the `usePublish` hook for it, It returns the `publish` method from [`liveProvider`](/api-references/providers/live-provider.md) under the hood.
```

2021-12-07 13:28 UTC, omeraplak requested changes

2021-12-07 15:03 UTC, omeraplak approved these changes

2021-12-07 15:14 UTC, closed without merging