WIP: Update index.ts
pankod/refine pull request #1378
Opened 2021-12-19 08:07 UTC by narayandreamer

Aggregation Filters patch
Aggregation Operation Spelling

**Closing issues**

Put `closes #1377` in your comment to auto-close the issue that your PR fixes (if such).

2021-12-20 07:11 UTC, omeraplak commented
Hey @narayandreamer ,
Great! Can we merge this PR? Or is it still in WIP status?

2021-12-20 07:49 UTC, narayandreamer commented
It's WIP, Could you tell me how to build dist folder in hasura package so that I can test and then remove WIP?

2021-12-20 08:14 UTC, omeraplak commented
> It's WIP, Could you tell me how to build dist folder in hasura package so that I can test and then remove WIP?

Ohh okay. Our document about local development,
https://refine.dev/docs/contributing/#running-in-development-mode

If you want to run specific projects you can use Lerna's filters,
https://github.com/lerna/lerna/tree/main/core/filter-options

Don't forget to make sure the path of the project you want to run is in `lerna.json`,
https://github.com/pankod/refine/blob/master/lerna.json#L2

For Hasura example,
```
{
  "packages": [
    "packages/*",
    "examples/dataProvider/hasura"
  ],
  "registry": "https://registry.npmjs.org/",
  "npmClient": "npm",
  "publishConfig": {
    "access": "public"
  },
  "version": "2.4.11"
}
```

example;
```
npm install
npm run bootstrap
npm run build
npm run start -- --scope @pankod/refine --scope @pankod/refine-hasura --scope refine-hasura-example
```

2021-12-28 09:16 UTC, omeraplak requested changes

2021-12-28 09:16 UTC, omeraplak commented on packages/hasura/src/index.ts
> +                    },
```suggestion
                    variables: {
                        where: {
                            value: hasuraFilters,
                            type: hasuraFiltersType,
                        },
                    },
```

2021-12-28 09:16 UTC, merged

2021-12-28 09:19 UTC, omeraplak commented
Hey @narayandreamer ,
We've tested your PR and works very well. Congrats! Thank you

2021-12-29 17:27 UTC, narayandreamer commented
Hi @omeraplak . Sorry I was AFK last week so couldn't update you. Cool it works