ID type update that supports string and number
pankod/refine pull request #1576
Opened 2022-02-22 13:09 UTC by salihozdemir

2022-02-22 15:29 UTC, omeraplak approved these changes

2022-02-23 08:49 UTC, omeraplak commented on packages/antd/src/components/buttons/show/index.tsx
> +    const id = recordItemId ?? decodeURIComponent(idFromRoute);
Why did we change it? In some GraphQL APIs, "id" can be base64.

https://github.com/pankod/refine/issues/1506

2022-02-23 08:52 UTC, salihozdemir commented on packages/antd/src/components/buttons/show/index.tsx
> +    const id = recordItemId ?? decodeURIComponent(idFromRoute);
Because, number is not decoding with `decodeURIComponent` so we changed it :)

2022-02-23 12:43 UTC, omeraplak requested changes

2022-02-23 12:43 UTC, omeraplak commented on packages/core/src/hooks/show/useShow.ts
> +        id ?? (idFromRoute !== undefined ? idFromRoute : undefined),
```suggestion
        id ?? idFromRoute,
```

2022-02-23 15:59 UTC, omeraplak approved these changes

2022-02-28 06:45 UTC, omeraplak approved these changes

2022-02-28 15:23 UTC, merged