Refactor react query keys
pankod/refine pull request #1583
Opened 2022-02-23 06:46 UTC by biskuvit

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

**Test plan (required)**

Demonstrate the code is solid. If not, please add `WIP:` in its title.

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2022-03-03 06:36 UTC, omeraplak requested changes

2022-03-03 06:36 UTC, omeraplak commented on packages/core/src/hooks/data/useDelete.ts
> +                            queryClient.invalidateQueries([resource]);
```suggestion
                            queryClient.removeQueries([resource]);
```

2022-03-04 12:39 UTC, omeraplak requested changes

2022-03-04 12:39 UTC, omeraplak commented on packages/core/src/hooks/data/useUpdate.ts
> +                                                    id: Number(id),
```suggestion
                                                    id: Number(id),
```
why do we convert id to number? id can be a string

2022-03-04 13:41 UTC, omeraplak commented on packages/core/src/hooks/data/useDeleteMany.ts
> +                        queryClient.removeQueries([resource, "detail", ids]);
Are we sure this is working?

2022-03-04 13:44 UTC, ozkalai commented on packages/core/src/hooks/data/useDeleteMany.ts
> +                        queryClient.removeQueries([resource, "detail", ids]);
I think we forgot to delete this point, you are right, we'll remove it. Thanks for your comment 🤸‍♀️

2022-03-04 16:27 UTC, omeraplak commented on packages/core/src/hooks/data/useDelete.ts
> +                    queryClient.removeQueries(detailQueries);
```suggestion
                queryClient.removeQueries([resource, "detail"]);
                queryClient.removeQueries([resource, "getMany"]);
```

2022-03-09 14:39 UTC, omeraplak approved these changes

2022-03-10 05:53 UTC, merged