Mui login form
pankod/refine pull request #1760
Opened 2022-04-26 16:36 UTC by ozkalai

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

**Test plan (required)**

Demonstrate the code is solid. If not, please add `WIP:` in its title.

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2022-04-27 07:53 UTC, omeraplak commented on packages/mui/src/components/pages/login/index.tsx
> +    const onSubmit: any = (data: ILoginForm) => login(data);
let's specify the type

2022-04-27 08:02 UTC, salihozdemir commented on examples/base/mui/src/App.tsx
> +    }, []);
[Mui System Preference](https://mui.com/material-ui/customization/dark-mode/#system-preference)

You can detect a theme by users preference like chrome or OS theme selection.

2022-04-27 08:05 UTC, salihozdemir commented on examples/base/mui/src/index.tsx
> +        <StylesProvider injectFirst>
Is `StylesProvider` the legacy styling solution for MUI isn't it?

2022-04-27 08:10 UTC, salihozdemir commented on packages/mui/src/components/pages/login/index.tsx
> +                                    }}
```suggestion
                                    sx={{
                                        fontWeight: "700",
                                        fontSize: "30px",
                                        letterSpacing: "-0.04px",
                                        lineHeight: "38px",
                                        color: text.secondary,
                                    }}
```

You don't have to use `useTheme` for getting the palette. You can see details in this [link](https://mui.com/system/basics/#shorthands)

2022-04-27 11:16 UTC, omeraplak approved these changes

2022-04-27 11:16 UTC, omeraplak requested changes

2022-04-27 11:16 UTC, omeraplak commented on examples/base/mui/src/index.tsx
> +import "@pankod/refine-mui/dist/styles.min.css";
we can move this to app.tsx

2022-04-28 06:22 UTC, omeraplak requested changes

2022-04-28 06:22 UTC, omeraplak commented on examples/base/mui/src/App.tsx
> +import "@pankod/refine-mui/dist/styles.min.css";
The import order should be like this,
https://github.com/pankod/refine/blob/master/examples/base/src/App.tsx#L9

2022-04-28 06:39 UTC, omeraplak commented on examples/base/mui/src/App.tsx
> +import "@pankod/refine-mui/dist/styles.min.css";
The import order should be like this,
https://github.com/pankod/refine/blob/master/examples/base/src/App.tsx#L9

2022-04-28 07:44 UTC, salihozdemir approved these changes

2022-04-28 09:26 UTC, omeraplak requested changes

2022-04-28 09:26 UTC, omeraplak commented on packages/mui/tsup.config.ts
> +import copyStaticFiles from "esbuild-copy-static-files";
```suggestion
```

2022-04-28 09:26 UTC, merged