[WIP] Mui fine foods products
pankod/refine pull request #1764
Opened 2022-04-27 15:10 UTC by ozkalai

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

**Test plan (required)**

Demonstrate the code is solid. If not, please add `WIP:` in its title.

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2022-04-28 06:11 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/products/list.tsx
> +                    ))}
```suggestion
                {tableQueryResult.data?.data.map((i: IProduct) => (
                        <Grid item xs={2} sm={3} md={3} key={i.id}>
                            <ProductItem
                                name={i.name}
                                key={i.id}
                                images={i.images}
                                price={i.price}
                                id={i.id}
                                description={i.description}
                                isActive={i.isActive}
                                createdAt={i.createdAt}
                                category={i.category}
                                stock={i.stock}
                            />
                        </Grid>
                    ))}
```

2022-04-28 06:11 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/products/list.tsx
> +                    ))}
would it be better?

2022-05-10 06:11 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/components/product/categoryFilter.tsx
> +            { ...filters[0] },
```suggestion
            { ...filters[0] },
```
why are we doing this?

2022-05-10 06:11 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/components/product/create.tsx
> +    const [uploadedImage, setUploadedImage] = useState(
Do we really need state?

2022-05-10 06:11 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/components/product/create.tsx
> +                <Typography fontWeight="bold">{t("Create Product")}</Typography>
do we have such a translate key? By the way, why don't we use the "create" crud component?

2022-05-10 06:11 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/products/list.tsx
> +    const paginationCount =
Can useTable provide the paginationCount? @salihozdemir

2022-05-10 06:11 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/products/list.tsx
> +            {categories?.data && (
What exactly does it have to do with categories?

2022-05-10 06:11 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/products/list.tsx
> +                                            { ...filters[1] },
why are we doing this?

2022-05-10 06:11 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/products/list.tsx
> +                            {categories?.data && (
why are we doing this?

2022-05-12 07:55 UTC, biskuvit approved these changes

2022-05-12 07:55 UTC, biskuvit commented on examples/fineFoods/admin/mui/src/App.tsx
> +import LocalPizzaIcon from "@mui/icons-material/LocalPizza";
```suggestion
import PeopleOutline, LocalPizza from "@mui/icons-material";
```

2022-05-12 07:55 UTC, biskuvit commented on examples/fineFoods/admin/mui/src/components/product/create.tsx
> +import CloseIcon from "@mui/icons-material/Close";
```suggestion
import Close from "@mui/icons-material";
```

2022-05-12 08:13 UTC, salihozdemir requested changes

2022-05-12 08:13 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/components/product/create.tsx
> +                                                        "Categoty required"
```suggestion
                                                        errors.category.message
```

2022-05-12 08:13 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/components/product/edit.tsx
> +                                                        "Categoty required"
```suggestion
                                                        errors.category.message
```

2022-05-12 08:13 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/products/list.tsx
> +
```suggestion
```

2022-05-12 08:13 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/products/list.tsx
> +
```suggestion
```

2022-05-12 08:13 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/products/list.tsx
> +
```suggestion
```

2022-05-12 08:13 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/products/list.tsx
> +
```suggestion
```

2022-05-12 09:04 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/components/product/create.tsx
> +    console.log("errors", errors);
console

2022-05-13 07:01 UTC, omeraplak approved these changes

2022-05-13 07:02 UTC, salihozdemir approved these changes

2022-05-13 07:06 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/components/product/create.tsx
> +    console.log("errors", errors);
```suggestion
```

2022-05-13 07:06 UTC, merged