Mui fine food couriers page
pankod/refine pull request #1795
Opened 2022-05-11 14:24 UTC by biskuvit

- [X] List Page
- [ ] Show Page
- [ ] Edit Page
- [ ] Create Page

2022-05-12 07:22 UTC, omeraplak approved these changes

2022-05-12 07:23 UTC, ozkalai approved these changes

2022-05-12 08:15 UTC, salihozdemir approved these changes

2022-05-12 08:19 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/couriers/list.tsx
> +                valueGetter: ({ row }) => row.gsm,
```suggestion
                
```
Field already gets the gsm.Is it necessary?

2022-05-12 08:20 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/couriers/list.tsx
> +            },
Field name is `order`but you show the email in this column. Seems a little confused.

2022-05-13 10:27 UTC, ozkalai approved these changes

2022-05-13 11:04 UTC, omeraplak requested changes

2022-05-13 11:04 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/couriers/list.tsx
> +                            {console.log("row", row)}
```suggestion
```

2022-05-13 11:04 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/couriers/list.tsx
> +        ],
```suggestion
```

2022-05-13 11:13 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/couriers/list.tsx
> +                valueGetter: ({ row }) => row.email,
Is this line necessary?

2022-05-13 11:13 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/couriers/list.tsx
> +                }}
```suggestion
                 onRowClick={({ id }) => {
                      show("orders", id);
                  }}
```
I think, you should use `onRowClick` instead of `onCellClick`.

2022-05-20 06:16 UTC, ozkalai commented on examples/fineFoods/admin/mui/src/pages/couriers/create.tsx
> +                                                    "Account Number must be 10 digits",
This limitation message should be added to locales.

2022-05-20 06:16 UTC, ozkalai commented on examples/fineFoods/admin/mui/src/pages/couriers/create.tsx
> +                                                    "Account Number must be 10 digits",
This limitation message should be added to locales.

2022-05-20 06:16 UTC, ozkalai commented on packages/mui/src/index.tsx
```suggestion
```

2022-05-20 06:16 UTC, ozkalai commented on examples/fineFoods/admin/mui/src/pages/couriers/create.tsx
> +                                                    "Vehicle Number is required",
```suggestion
                                                   t(
                                                        "errors.required.field",
                                                        { field: "Vehicle Number" },
                                                    ),
```

2022-05-20 06:16 UTC, ozkalai commented on examples/fineFoods/admin/mui/src/pages/couriers/create.tsx
> +                                                                "invalid email address",
This validation message should be added to locales.

2022-05-20 11:41 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/couriers/show.tsx
> +                    <List cardHeaderProps={{ title: t("orders.orders") }}>
```suggestion
                    <List cardHeaderProps={{ title: t("orders.orders") }}>
```
As in Ant design example we should hide `<CreateButton>`, https://github.com/pankod/refine/blob/master/examples/fineFoods/admin/src/pages/couriers/show.tsx#L112

2022-05-20 11:41 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/couriers/show.tsx
> +                        <DataGrid
DataGrid rows appear to be selectable but why?

2022-05-20 12:14 UTC, omeraplak approved these changes

2022-05-20 12:21 UTC, ozkalai approved these changes

2022-05-20 12:25 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/couriers/list.tsx
> +            },
field name is `comment` but the column shows the address. You can rename it like `address` etc.

2022-05-20 12:27 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/couriers/list.tsx
> +        <List canCreate>
```suggestion
        <List>
```
Is it necessary?

2022-05-20 12:28 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/couriers/show.tsx
> +            },
+1, field name and shows value names not match correctly.

2022-05-20 12:29 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/couriers/show.tsx
> +            },
+1

2022-05-20 12:42 UTC, salihozdemir approved these changes

2022-05-20 13:18 UTC, merged