Mui - fine foods example stores page created
pankod/refine pull request #1796
Opened 2022-05-11 15:24 UTC by ozkalai

Hey, I'm client! Test me! 'MUI'
[Link to MUI-FINE-FOODS-STORE](https://mui-fin-client.refine.pankod.com)

Test me! 'MUI'
[Link to MUI-FINE-FOODS-STORE](https://mui-fin-refine.pankod.com)

Hey, I'm client! Test me! 'MUI'
[Link to MUI-FINE-FOODS-STORE](https://mui-fin-client.refine.pankod.com)

Test me! 'MUI'
[Link to MUI-FINE-FOODS-STORE](https://mui-fin-refine.pankod.com)

Test me! 'MASTER'
[Link to MUI-FINE-FOODS-STORE](https://mui-fin-refine.pankod.com)

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

**Test plan (required)**

Demonstrate the code is solid. If not, please add `WIP:` in its title.

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2022-05-12 07:25 UTC, biskuvit requested changes

2022-05-12 07:25 UTC, biskuvit commented on examples/fineFoods/admin/mui/src/pages/stores/list.tsx
> +
space

2022-05-12 07:25 UTC, biskuvit commented on examples/fineFoods/admin/mui/src/pages/stores/list.tsx
> +import { IStore } from "interfaces";
this import should under the global imports

2022-05-12 08:23 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/stores/list.tsx
> +            },
```suggestion
            {
                field: "address",
                headerName: t("stores.fields.address"),
                flex: 2,
                valueGetter: ({ row }) => row.address.text,
            },
```

If you don't return the React.Node, you can use `valueGetter` instead of `renderCell` for string values.

2022-05-12 08:27 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/stores/list.tsx
> +            },
```suggestion
            {
                field: "isActive",
                headerName: t("stores.fields.isActive"),
                flex: 0.5,
                // eslint-disable-next-line react/display-name
                renderCell: ({ row }) => <BooleanField value={row.isActive} />,
            },
```

You can use `<BooleanField>` instead of Icons.

2022-05-16 09:41 UTC, biskuvit approved these changes

2022-05-16 09:41 UTC, biskuvit commented on examples/fineFoods/admin/mui/src/pages/stores/create.tsx
> +export const StoreCreate: React.FC = () => {
we can add IResourceComponentsProps

2022-05-16 09:41 UTC, biskuvit commented on examples/fineFoods/admin/mui/src/pages/stores/list.tsx
> +                    // />,
do you need this

2022-05-16 09:41 UTC, biskuvit commented on examples/fineFoods/admin/mui/src/pages/stores/list.tsx
> +                    // />,
do you need this

2022-05-16 11:43 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/components/product/item.tsx
> +                                updateStock(parseInt(e.target.value), product);
```suggestion
                                updateStock(parseInt(e.target.value, 10), product);
```

2022-05-16 11:43 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/components/store/storeProducts.tsx
> +    });
```suggestion
        modal: { visible, close, show, saveButtonProps },
        register,
        refineCore: { onFinish },
        formState: { errors },
        handleSubmit,
        watch,
        setValue,
        control,
    } = useModalForm<IProduct>({
        refineCoreProps: { action: "create" },
    });
```
maybe we can use `create` prefix for props.
like, `createDrawerVisible`

2022-05-16 11:43 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/components/store/storeProducts.tsx
> +        refineCoreProps: { action: "edit" },
```suggestion
        refineCoreProps: { action: "edit" },
```
In the Ant Design version, we have given redirect as false. No need here?
https://github.com/pankod/refine/blob/master/examples/fineFoods/admin/src/components/store/storeProducts.tsx#L112

2022-05-16 11:43 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/stores/create.tsx
> +            resource: "stores",
Do we need to pass resource name?

2022-05-16 11:43 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/stores/create.tsx
> +            saveButtonProps={{
`saveButtonProps` is now available from `useForm`.
https://github.com/pankod/refine/pull/1803

2022-05-16 11:43 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/stores/create.tsx
> +                                        required: "Email is required",
we must use translate or generic error message

2022-05-16 11:43 UTC, merged