Mui fine foods store2
pankod/refine pull request #1808
Opened 2022-05-16 16:53 UTC by ozkalai

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

**Test plan (required)**

Demonstrate the code is solid. If not, please add `WIP:` in its title.

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2022-05-17 06:43 UTC, omeraplak requested changes

2022-05-17 06:43 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/stores/create.tsx
> +                                    rules={{ required: "Selection required" }}
translate

2022-05-17 12:14 UTC, salihozdemir approved these changes

2022-05-17 12:45 UTC, omeraplak commented on packages/mui/src/components/crud/edit/index.tsx
> +                    <Typography sx={{ fontSize: "20px", fontWeight: 600 }}>
Wouldn't it be better to use `h5` instead? as in the original, https://github.com/mui/material-ui/blob/master/packages/mui-material/src/CardHeader/CardHeader.js#L95

2022-05-17 12:46 UTC, ozkalai commented on packages/mui/src/components/crud/edit/index.tsx
> +                    <Typography sx={{ fontSize: "20px", fontWeight: 600 }}>
make sense :)

2022-05-17 13:53 UTC, ozkalai commented on packages/mui/src/components/crud/edit/index.tsx
> +                    <Typography sx={{ fontSize: "20px", fontWeight: 600 }}>
Do you think we should set a specific font weight ( 600 ) for the "h5" variant on Theme in the future? If not I am gonna pass as a prop.

2022-05-20 05:37 UTC, omeraplak approved these changes

2022-05-20 05:37 UTC, merged