categories page table init
pankod/refine pull request #1829
Opened 2022-05-24 07:07 UTC by biskuvit

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

**Test plan (required)**

Demonstrate the code is solid. If not, please add `WIP:` in its title.

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2022-05-24 14:27 UTC, omeraplak approved these changes

2022-05-25 06:29 UTC, ozkalai commented on examples/fineFoods/admin/mui/src/pages/categories/list.tsx
> +import { ICategory, ICourier, IProduct } from "interfaces";
local import should relocate

2022-05-25 06:29 UTC, ozkalai commented on examples/fineFoods/admin/mui/src/pages/categories/list.tsx
> +
```suggestion
```

2022-05-25 06:29 UTC, ozkalai commented on examples/fineFoods/admin/mui/src/pages/categories/list.tsx
> +
```suggestion
```

2022-05-25 06:29 UTC, ozkalai commented on examples/fineFoods/admin/mui/src/pages/categories/list.tsx
> +                Cell: ({ row }: any) => {
could we specify the type?

2022-05-25 06:29 UTC, ozkalai commented on examples/fineFoods/admin/mui/src/pages/categories/list.tsx
> +                Cell: ({ value }: any) => <BooleanField value={value} />,
the type needs to specify

2022-05-25 06:29 UTC, ozkalai commented on examples/fineFoods/admin/mui/src/pages/categories/list.tsx
> +                Cell: ({ value }: any) => {
the type needs to specify

2022-05-25 06:29 UTC, ozkalai commented on examples/fineFoods/admin/mui/src/pages/categories/list.tsx
> +                    onPageChange={(event: unknown, newPage: number) =>
Could we specify the event type?

2022-05-25 13:23 UTC, salihozdemir commented on examples/fineFoods/admin/mui/src/pages/categories/list.tsx
> +import { ICategory, IProduct } from "interfaces";
```suggestion

import { ICategory, IProduct } from "interfaces";
```

2022-05-25 13:32 UTC, salihozdemir approved these changes

2022-05-26 06:20 UTC, ozkalai approved these changes

2022-05-26 06:21 UTC, omeraplak requested changes

2022-05-26 06:21 UTC, omeraplak commented on examples/fineFoods/admin/mui/src/pages/categories/list.tsx
> +    const renderEditRow = useCallback(
apparently there are lint errors

2022-05-26 07:24 UTC, omeraplak approved these changes

2022-05-26 07:24 UTC, merged