docs: add mui tutorial and example
pankod/refine pull request #1882
Opened 2022-06-02 14:10 UTC by biskuvit

I am going to create a material-ui tutorial.

- [X] Example
- [X] Documentation
- [x] Documentation images

https://codesandbox.io/embed/github/pankod/refine/tree/next/examples/tutorial/mui

2022-06-02 14:38 UTC, omeraplak requested changes

2022-06-02 14:38 UTC, omeraplak commented on documentation/docs/ui-frameworks/mui/tutorial.md
> +**refine** uses [Material UI](https://mui.com/x/react-data-grid/#mit-version) components to render data.
here we can specify that we also support the `<DataGridPro />` component

2022-06-02 14:38 UTC, omeraplak commented on documentation/docs/ui-frameworks/mui/tutorial.md
> +:::
```suggestion
```

2022-06-09 07:24 UTC, yildirayunlu requested changes

2022-06-09 07:24 UTC, yildirayunlu commented on .changeset/kind-cameras-lick.md
> +create refine [material ui tutorial](https://refine.dev/docs/ui-frameworks/mui/tutorial/) with [example](https://github.com/pankod/refine/tree/master/examples/tutorial/mui)
For example, don't add changeset.

2022-06-09 08:11 UTC, salihozdemir commented on documentation/docs/ui-frameworks/mui/tutorial.md
> +                    helperText={errors?.title?.message}
```suggestion
                    {...register("title", { required: "This field is required" })}
                    error={!!errors.title}
                    helperText={errors.title?.message}
```

2022-06-09 08:11 UTC, salihozdemir commented on documentation/docs/ui-frameworks/mui/tutorial.md
> +                    defaultValue={" "}
```suggestion
                   
```

Is it necessary?

2022-06-09 08:11 UTC, salihozdemir commented on documentation/docs/ui-frameworks/mui/tutorial.md
> +                />
```suggestion
                <Controller
                    control={control}
                    name="status"
                    rules={{ required: "This field is required" }}
                    render={({ field }) => (
                        <Autocomplete
                            {...field}
                            options={["published", "draft", "rejected"]}
                            onChange={(_, value) => {
                                field.onChange(value);
                            }}
                            renderInput={(params) => (
                                <TextField
                                    {...params}
                                    label="status"
                                    margin="normal"
                                    variant="outlined"
                                    error={!!errors.status}
                                    helperText={errors.status?.message}
                                    required
                                />
                            )}
                        />
                    )}
                />
```

2022-06-09 08:11 UTC, salihozdemir commented on documentation/docs/ui-frameworks/mui/tutorial.md
> +                    defaultValue=""
```suggestion
                    rules={{ required: "This field is required" }}
```

2022-06-09 08:11 UTC, salihozdemir commented on documentation/docs/ui-frameworks/mui/tutorial.md
> +                                    }
```suggestion
                                    helperText={errors.category?.message}
```

2022-06-09 08:11 UTC, salihozdemir commented on documentation/docs/ui-frameworks/mui/tutorial.md
> +    );
```suggestion 
    return (
        <List>
            <DataGrid {...dataGridProps} autoHeight />
        </List>
    );
```

2022-06-09 08:48 UTC, ozkalai commented on documentation/docs/ui-frameworks/antd/tutorial.md
> +✳️ Save button submits the form by executing the `useUpdate` method provided by the [`dataProvider`](/core/providers/data-provider.md). After a successfull response, the application will be redirecte
```suggestion
✳️ Save button submits the form by executing the `useUpdate` method provided by the [`dataProvider`](/core/providers/data-provider.md). After a successful response, the application will be redirected to the listing page.
```

2022-06-09 08:48 UTC, ozkalai commented on examples/tutorial/mui/src/pages/posts/list.tsx
> +            field: "category.id",
you might have to add flex key for wider screen.

2022-06-09 08:48 UTC, ozkalai commented on examples/tutorial/mui/src/pages/posts/list.tsx
> +            minWidth: 150,
you might have to add flex key for wider screen.

2022-06-09 08:48 UTC, ozkalai commented on examples/tutorial/mui/src/pages/posts/list.tsx
> +            minWidth: 220,
you might have to add flex key for wider screen.

2022-06-09 08:48 UTC, ozkalai commented on examples/tutorial/mui/src/pages/posts/list.tsx
> +            minWidth: 250,
you might have to add flex key for wider screen.

2022-06-09 08:58 UTC, biskuvit commented on documentation/docs/ui-frameworks/mui/tutorial.md
> +                    defaultValue={" "}
Actually, It's required to get the default value

2022-06-09 10:12 UTC, aliemir commented on examples/tutorial/mui/src/pages/posts/edit.tsx
> +            saveButtonProps={{ onClick: handleSubmit(onFinish) }}
```suggestion
        saveButtonProps,
        control,
        formState: { errors },
    } = useForm();

    const { autocompleteProps } = useAutocomplete<ICategory>({
        resource: "categories",
        defaultValue: queryResult?.data?.data.category.id,
        queryOptions: { enabled: !!queryResult?.data?.data.category.id },
    });

    return (
        <Edit
            isLoading={formLoading}
            saveButtonProps={saveButtonProps}
```

2022-06-09 10:38 UTC, omeraplak approved these changes

2022-06-09 11:21 UTC, omeraplak requested changes

2022-06-09 11:21 UTC, omeraplak commented on documentation/docs/ui-frameworks/mui/tutorial.md
> +<iframe src="https://codesandbox.io/embed/github/pankod/refine/tree/next/examples/tutorial/mui?autoresize=1&fontsize=14&theme=dark&view=preview"
```suggestion
<iframe src="https://codesandbox.io/embed/github/pankod/refine/tree/master/examples/tutorial/mui?autoresize=1&fontsize=14&theme=dark&view=preview"
```

2022-06-09 12:16 UTC, salihozdemir commented on examples/tutorial/mui/src/index.tsx
> +`;
I think, we should move it to the `App.tsx`

2022-06-09 12:18 UTC, salihozdemir commented on documentation/docs/ui-frameworks/mui/tutorial.md
> +            />
Should we add the `notificationProvider`?

2022-06-09 12:19 UTC, salihozdemir commented on documentation/docs/ui-frameworks/mui/tutorial.md
> +To get more detailed information about this hook, please refer the [useOne Documentation](#).
```suggestion
To get more detailed information about this hook, please refer the [useOne Documentation](#).
```
Missing link

2022-06-09 12:35 UTC, salihozdemir approved these changes

2022-06-09 14:15 UTC, omeraplak commented on documentation/docs/ui-frameworks/mui/tutorial.md
> +To see how the filtering works and more detail, you can look at the [`useDataGrid`](/ui-frameworks/mui/hooks/useDataGrid.md) hook.
```suggestion
To see how the filtering works and more detail, you can look at the [`useDataGrid`](/ui-frameworks/mui/hooks/useDataGrid.md#sorting) hook.
```

2022-06-09 14:15 UTC, omeraplak commented on documentation/docs/ui-frameworks/mui/tutorial.md
> +To see how the filtering works and more detail, you can look at the [`useDataGrid`](/ui-frameworks/mui/hooks/useDataGrid.md) hook.
I'm not sure about this syntax but my goal is to post it in the sorting section

2022-06-09 15:08 UTC, aliemir approved these changes

2022-06-10 06:32 UTC, merged