feat: `useMenu` hook in `@pankod/refine-core`
pankod/refine pull request #1952
Opened 2022-06-14 14:37 UTC by aliemir

Move `useMenu` hook from UI packages to `@pankod/refine-core`.

2022-06-16 11:29 UTC, omeraplak commented on documentation/docs/core/hooks/ui/useMenu.md
> +[Material UI > Customization > Custom Sider&#8594](#)
```suggestion
[Ant Design > Customization > Custom Sider&#8594](#)

[Material UI > Customization > Custom Sider&#8594](#)
```

2022-06-16 11:29 UTC, omeraplak commented on documentation/docs/core/hooks/ui/useMenu.md
> +```tsx title="components/Layout.tsx"
```suggestion
```tsx title="components/layout.tsx"
```

2022-06-17 07:43 UTC, salihozdemir commented on documentation/docs/core/hooks/ui/useMenu.md
> +            ]}
I think, resource pages should have import path.

2022-06-17 07:43 UTC, salihozdemir commented on documentation/docs/core/hooks/ui/useMenu.md
> +```tsx title="components/Layout.tsx"
```suggestion
```tsx title="src/components/Layout.tsx"
```

2022-06-17 07:43 UTC, salihozdemir commented on documentation/docs/ui-frameworks/antd/customization/layout.md
> +                </AntdLayout>
```suggestion
            Layout={({ children }) => (
                <AntdLayout>
                    <AntdLayout.Header>
                        <CustomSider />
                    </AntdLayout.Header>
                    <AntdLayout.Content>
                        <AntdLayout.Content>
                            <div style={{ padding: 24, minHeight: 360 }}>
                                {children}
                            </div>
                        </AntdLayout.Content>
                    </AntdLayout.Content>
                </AntdLayout>
```

By default, `Footer` and `OffLayoutArea` return null. I think, we can remove them for no confusing.

2022-06-17 07:43 UTC, salihozdemir commented on examples/customization/customTheme/mui/public/index.html
> +        <title>Material UI base example</title>
```suggestion
        <title>Material UI custom theme example</title>
```

2022-06-17 07:43 UTC, salihozdemir commented on examples/customization/customTheme/mui/public/manifest.json
> +    "name": "Material UI base example",
```suggestion
    "short_name": "Material UI custom theme example",
    "name": "Material UI custom theme example",
```

2022-06-17 07:43 UTC, salihozdemir commented on examples/customization/customTheme/mui/src/pages/posts/create.tsx
> +                    defaultValue=""
```suggestion
                   
```

2022-06-17 07:43 UTC, salihozdemir commented on examples/customization/customTheme/mui/src/pages/posts/edit.tsx
> +                    defaultValue=""
```suggestion
                    defaultValue={null}
```

2022-06-17 08:20 UTC, aliemir commented
Updated live examples from CodeSandbox to StackBlitz as in #1981

2022-06-17 08:26 UTC, aliemir commented on documentation/docs/core/hooks/ui/useMenu.md
> +            ]}
Added imports to the top 👍

2022-06-17 08:29 UTC, aliemir commented on documentation/docs/ui-frameworks/antd/customization/layout.md
> +                </AntdLayout>
Even if they are null, the aim is to replicate the default layout in the custom layout example to give a better starting point to customize for users. By removing those in a custom layout, we will lose the functionality on `OffLayoutArea` and `Footer` props in `<Refine/>` component.

2022-06-17 08:53 UTC, salihozdemir approved these changes

2022-06-17 08:53 UTC, salihozdemir commented on documentation/docs/core/hooks/ui/useMenu.md
> +
```suggestion

import { PostList, PostCreate, PostEdit, PostShow } from "pages/post";
import { CategoryList, CategoryCreate, CategoryEdit } from "pages/category";
```

2022-06-17 08:53 UTC, salihozdemir commented on documentation/docs/core/hooks/ui/useMenu.md
> +This hook can also be used to build custom menus, including multi-level support. `<Sider/>` components inside [`@pankod/refine-antd`](#) and [`@pankod/refine-mui`](#) packages are using this hook as
Missing links

2022-06-17 08:53 UTC, salihozdemir commented on documentation/docs/core/hooks/ui/useMenu.md
> +[Material UI > Customization > Custom Sider &#8594](#)
Missing links

2022-06-17 09:20 UTC, ozkalai approved these changes

2022-06-17 10:13 UTC, omeraplak requested changes

2022-06-17 10:13 UTC, omeraplak commented on documentation/docs/core/hooks/ui/useMenu.md
> +Create a `<Layout />` component inside `src/components/Layout.tsx` with the following code;
```suggestion
Create a `<Layout />` component inside `src/components/layout.tsx` with the following code;
```

2022-06-17 10:13 UTC, omeraplak commented on documentation/docs/core/hooks/ui/useMenu.md
> +We created a header with a logo and a list of links to all menu items (resources). The links are clickable and will navigate to the corresponding resource. To do this, we used the [`useMenu`](/core/h
```suggestion
We created a header with a logo and a list of links to all menu items (resources). The links are clickable and will navigate to the corresponding resource. To do this, we used the [`useMenu`](/core/hooks/ui/useMenu.md) hook to get the menu items from the `<Refine/>` and the `useRouterContext` hook to get the `<Link/>` component from the router provider. Also [`useNavigation`](/core/hooks/navigation/useNavigation.md) hook can be used to navigate between routes.
```

2022-06-17 10:13 UTC, omeraplak commented on documentation/docs/ui-frameworks/mui/customization/sider.md
> +id: sider
```suggestion
id: mui-sider
```
must be unique

2022-06-17 10:13 UTC, omeraplak commented on documentation/docs/ui-frameworks/antd/customization/sider.md
> +id: sider
```suggestion
id: antd-sider
```

2022-06-17 12:24 UTC, omeraplak approved these changes

2022-06-17 12:24 UTC, merged