chore(examples): reordering folders
pankod/refine pull request #2019
Opened 2022-06-21 14:31 UTC by ozkalai

in this PR, We have reordered the examples' folders separately as Ant Design ( `antd` ) and Material UI ( `mui` ).

2022-06-21 14:32 UTC, aliemir commented on documentation/blog/2021-10-6-migrating-react-admin-application-to-refine.md
>  [refine](https://refine.dev/) is an extremely customizable [Ant Desig](https://ant.design/) based [React](https://reactjs.org/) framework for data-intensive applications and it handles most of the CR
```suggestion
[refine](https://refine.dev/) is an extremely customizable [Ant Design](https://ant.design/) based [React](https://reactjs.org/) framework for data-intensive applications and it handles most of the CRUD functionality that can be a requirement in many applications, without much effort. Providing the rest of the desired functionality (outside CRUD) is up to you, like in any <strong>React</strong> application.
```

2022-06-21 14:34 UTC, aliemir approved these changes

2022-06-21 14:39 UTC, ozkalai commented on examples/importExport/mui/src/App.tsx
> +            <CssBaseline />
I think there is no need to add font smoothing here, I checked the sider collapse behavior and it works properly.

2022-06-22 05:51 UTC, omeraplak commented
Hey @ozkalai,
Can we move "baseHeadless" folder to "headless" in "base"?

2022-06-22 05:52 UTC, omeraplak commented on examples/importExport/mui/src/App.tsx
> +            <CssBaseline />
Is `WebkitFontSmoothing` related to Sider?

https://github.com/pankod/refine/blob/next/examples/base/mui/src/App.tsx#L23

2022-06-22 07:15 UTC, ozkalai commented on examples/importExport/mui/src/App.tsx
> +            <CssBaseline />
I can't see any difference between auto smoothing and without it.

2022-06-22 08:29 UTC, omeraplak requested changes

2022-06-22 08:29 UTC, omeraplak commented on examples/importExport/mui/src/pages/list.tsx
> +        },
```suggestion
            open?.({
                    message: "Import successfully completed",
                    type: "success",
                });
        },
```

2022-06-22 09:48 UTC, merged