Audit log
pankod/refine pull request #2049
Opened 2022-06-24 10:54 UTC by yildirayunlu

Add auditLogProvider docs.

2022-06-24 11:52 UTC, salihozdemir commented on documentation/docs/core/hooks/audit-log/useLog.md
> +If you need to create an audit log, **refine** provides the useLog hook for it. Returns two mutations `log` and `rename`, the method to create or update from [`auditLogProvider`](/core/providers/audi
```suggestion
If you need to create an audit log, **refine** provides the useLog hook for it. Returns two mutations `log` and `rename` that the methods uses `create` or `update` from [`auditLogProvider`](/core/providers/audit-log-provider.md#create) under the hood.
```

2022-06-24 11:52 UTC, salihozdemir commented on documentation/docs/core/hooks/audit-log/useLog.md
> +```tsx
```suggestion
## `log`

If you need to create an audit-log, you can use the `useLog` hook's `create` method. It returns the `create` method from [auditLogProvider](https://pankod-refine-documentation-pr-2049.surge.sh/docs/core/providers/audit-log-provider/) under the hood.

```tsx
```

2022-06-24 11:52 UTC, salihozdemir commented on documentation/docs/core/hooks/audit-log/useLog.md
> +If you need to update the audit-log, you can use the `useLog` hook `rename` method. It returns the `update` method from [`auditLogProvider`](/core/providers/audit-log-provider.md) under the hood.
```suggestion
If you need to update the audit-log, you can use the `useLog` hook's `rename` method. It returns the `update` method from [`auditLogProvider`](/core/providers/audit-log-provider.md) under the hood.
```

2022-06-24 11:52 UTC, salihozdemir commented on documentation/docs/core/providers/audit-log-provider.md
> +**refine** provides Audit Log support via `auditLogProvider`. A new log record is automatically created when a new record is created, updated and deleted. You can access these records from anywhere v
```suggestion
**refine** provides Audit Log support via `auditLogProvider`. A new log record is automatically created when a new record is created, updated and deleted. You can access these records from anywhere via hooks. You can also manually create or update an audit-log via hooks.
```

2022-06-24 11:52 UTC, salihozdemir commented on documentation/docs/core/providers/audit-log-provider.md
> +Complete all this by writing an `audit-log-provider` to **refine**. This provider must include following methods:
```suggestion
Complete all this by writing an `auditLogProvider` to **refine**. This provider must include following methods:
```

2022-06-24 11:52 UTC, salihozdemir commented on documentation/docs/core/providers/audit-log-provider.md
> +        meta: Record<number | string, any>;
```suggestion
        meta?: Record<number | string, any>;
```

2022-06-24 11:52 UTC, salihozdemir commented on documentation/docs/core/providers/audit-log-provider.md
> +You must pass a audit log provider to the `auditLogProvider` prop of `<Refine>`.
```suggestion
You must pass an `auditLogProvider` prop to `<Refine>`.
```

2022-06-24 11:52 UTC, salihozdemir commented on documentation/docs/core/providers/audit-log-provider.md
> +## Creating a audit log provider
```suggestion
## Creating an audit log provider
```

2022-06-24 11:52 UTC, salihozdemir commented on documentation/docs/core/providers/audit-log-provider.md
> +This method is triggered when a new log is created. The incoming parameters contain the data we need and we need to return a Promise.
```suggestion
This method is triggered when a new log is created or when you use `useLog`'s `log` method. The incoming parameters show the values of the new record to be created.
```

2022-06-24 13:15 UTC, omeraplak requested changes

2022-06-24 13:15 UTC, omeraplak commented on documentation/docs/core/providers/audit-log-provider.md
> +        const { data } = await dataProvider(API_URL).getList({
here we should tell the data provider more

2022-06-24 13:15 UTC, omeraplak commented on documentation/docs/core/providers/audit-log-provider.md
> +We recommend that you create audit logs server-side. So when the user performs an action (create, createMany, update, updateMany, delete and deleteMany), we recommend that you do it on the API side.
The explanation is repetitive. We can explain why.

2022-06-24 13:15 UTC, omeraplak commented on documentation/docs/core/providers/audit-log-provider.md
> +The `id` of the record created in the `meta` object is added. It is used for filtering purposes.
Do we need to talk about the filtering part?

2022-06-24 13:15 UTC, omeraplak commented on documentation/docs/core/hooks/audit-log/useLog.md
> +If you need to create an audit-log, you can use the `useLog` hook's `create` method. It returns the `create` method from [auditLogProvider](https://pankod-refine-documentation-pr-2049.surge.sh/docs/c
```suggestion
If you need to create an audit log, you can use the `useLog` hook's `create` method. It returns the `create` method from [auditLogProvider](https://pankod-refine-documentation-pr-2049.surge.sh/docs/core/providers/audit-log-provider/) under the hood.
```

2022-06-27 10:31 UTC, yildirayunlu commented on documentation/docs/core/providers/audit-log-provider.md
> +## Manage
Maybe a better title?

2022-06-27 10:59 UTC, omeraplak requested changes

2022-06-27 10:59 UTC, omeraplak commented on documentation/docs/core/providers/audit-log-provider.md
> +We recommend that you create audit logs on the server side for cors security concern. Because data can be changed on the client-side.
```suggestion
We recommend you create `Audit logs` on the API side for security concerns because data can be changed on the client side.
```

2022-06-27 10:59 UTC, omeraplak commented on documentation/docs/core/providers/audit-log-provider.md
> +This method is triggered when a new log is created or when you use `useLog`'s `log` method. The incoming parameters show the values of the new record to be created.
```suggestion
This method is triggered when a new successful mutation or when you use `useLog`'s `log` method. The incoming parameters show the values of the new record to be created.
```

2022-06-27 10:59 UTC, omeraplak commented on documentation/docs/core/providers/audit-log-provider.md
> +When we test, we will see that an object like the one below is created in the `logs` resource.
```suggestion
When a successful create mutation, the `create` method will be called with the following parameters.
```

2022-06-27 10:59 UTC, omeraplak commented on documentation/docs/core/providers/audit-log-provider.md
> +```json
we can make two tabs here, like usage and output

https://refine.dev/docs/guides-and-concepts/data-provider/graphql/#list-page

2022-06-28 06:41 UTC, aliemir approved these changes

2022-06-28 06:58 UTC, biskuvit commented on documentation/docs/core/hooks/audit-log/useLog.md
> +If you need to create an audit log, **refine** provides the useLog hook for it. Returns two mutations `log` and `rename` that the methods uses `create` or `update` from [`auditLogProvider`](/core/pro
```suggestion
If you need to create an audit log, **refine** provides the `useLog` hook for it. Returns two mutations `log` and `rename` that the methods uses `create` or `update` from [`auditLogProvider`](/core/providers/audit-log-provider.md#create) under the hood.
```

2022-06-28 06:58 UTC, biskuvit commented on documentation/docs/core/providers/audit-log-provider.md
> +Complete all this by writing an `auditLogProvider` to **refine**. This provider must include following methods:
```suggestion
Complete all this by writing an `auditLogProvider` to **refine**. This provider must include the following methods:
```

2022-06-28 06:58 UTC, biskuvit commented on examples/auditLogProvider/src/interfaces/index.d.ts
> +    id: string;
Shouldn't ids be the `Basekey`?

2022-06-28 08:01 UTC, salihozdemir commented on documentation/docs/core/providers/audit-log-provider.md
> +## Manage
`Manage Log Permissions` is it good? 😅

2022-06-28 08:03 UTC, salihozdemir approved these changes

2022-06-28 08:19 UTC, omeraplak commented on documentation/docs/core/providers/audit-log-provider.md
> +## Manage
`Enable for specific mutations type` is it good? 👀

2022-06-28 08:20 UTC, omeraplak commented on documentation/docs/core/providers/audit-log-provider.md
> +        const { data } = await dataProvider(API_URL).getList({
we must show how we defined dataProvider

2022-06-28 12:35 UTC, yildirayunlu commented on documentation/docs/core/providers/audit-log-provider.md
> +## Manage
> `Manage Log Permissions` is it good? 😅

```
options: {
    auditLog: {
        permissions: ["create"],
    },
},
```

@salihozdemir We can change `permission` keyword.

2022-06-30 05:27 UTC, aliemir commented
Any updates on this one? @yildirayunlu @omeraplak

2022-07-06 07:43 UTC, ozkalai approved these changes

2022-07-06 09:16 UTC, omeraplak approved these changes

2022-07-06 09:18 UTC, merged