refactor(strapi-v4): fixed dataProvider getList method return value
pankod/refine pull request #2050
Opened 2022-06-24 11:34 UTC by ozkalai

In this PR, We have fixed `total` return value of `@pankod/refine-strapi-v4` dataProvider `getList` method.

2022-06-24 11:35 UTC, aliemir approved these changes

2022-06-24 11:41 UTC, omeraplak requested changes

2022-06-24 11:41 UTC, omeraplak commented on .changeset/green-poems-grab.md
> +Resolves [#2028](https://github.com/pankod/refine/issues/2028)
```suggestion
Fix pagination issue on `users` endpoint - [#2028](https://github.com/pankod/refine/issues/2028)
```

2022-06-24 11:55 UTC, salihozdemir approved these changes

2022-06-27 06:18 UTC, biskuvit approved these changes

2022-06-28 06:17 UTC, omeraplak requested changes

2022-06-28 06:17 UTC, omeraplak commented on packages/airtable/src/index.ts
> +                        typeof current !== "undefined" &&
I think it is not correct to make this check on all data providers. We have to find a different solution

2022-06-28 06:17 UTC, omeraplak commented on packages/antd/src/hooks/table/useTable/useTable.ts
> +            pagination: hasPagination
Not a suitable scope for ternary if

2022-06-28 06:17 UTC, omeraplak commented on packages/mui/src/hooks/useDataGrid/index.ts
> +            ...(hasPagination
Not a suitable scope for ternary if

2022-06-28 06:17 UTC, omeraplak commented on packages/supabase/src/index.ts
> +                total: count || data?.length || 0,
why do we return data length if there is no count?

2022-06-28 10:34 UTC, biskuvit commented on packages/react-table/src/useTable/index.ts
> +    props: UseTableProps<TData, TError> & { hasPagination?: true },
```suggestion
    props: UseTableProps<TData, TError> & { hasPagination?: boolean },
```
should it be like this?

2022-06-28 13:44 UTC, aliemir commented on packages/react-table/src/useTable/index.ts
> +    props: UseTableProps<TData, TError> & { hasPagination?: true },
This is actually done for overloading the function; `useTable` returns different values by the `hasPagination` value. For `current`, `pageSize` etc. we return `undefined` if pagination is disabled, otherwise they return `number` and `React.Dispatch`

2022-06-29 07:16 UTC, yildirayunlu commented on .changeset/chatty-peaches-cheer.md
> +Updated `useDataGrid` hook with `hasPagination` to enable/disable pagination.
We can add simple use case.

2022-06-29 07:16 UTC, yildirayunlu commented on .changeset/stupid-meals-yell.md
> +Updated `useList` config with no pagination option. Set `pagination` to `false` to disable pagination.
We can add simple use case.

2022-06-29 10:29 UTC, aliemir commented on .changeset/chatty-peaches-cheer.md
> +Updated `useDataGrid` hook with `hasPagination` to enable/disable pagination.
Updated with more details

2022-06-29 10:29 UTC, aliemir commented on .changeset/stupid-meals-yell.md
> +Updated `useList` config with no pagination option. Set `pagination` to `false` to disable pagination.
Updated with more details on use case and implementation.

2022-06-29 13:05 UTC, merged