feat: add telemetry
pankod/refine pull request #2078
Opened 2022-06-30 14:45 UTC by yildirayunlu

Telemetry support is add in this pr. You can turn off at any time with `disableTelemetry`.

2022-07-04 08:18 UTC, omeraplak commented on packages/core/tsup.config.ts
> +                    const versionRegex = /const REFINE_VERSION = "\d.\d.\d";/gm;
```suggestion
                    const versionRegex = /const REFINE_VERSION = "\d.\d.\d";/gm;
```
Should we consider this part as a separate plugin?

2022-07-04 13:43 UTC, omeraplak requested changes

2022-07-04 13:43 UTC, omeraplak commented on packages/core/src/interfaces/telementry.ts
> +        accessControlProvider?: boolean;
```suggestion
        auth?: boolean;
        data?: boolean;
        router?: boolean;
        notification?: boolean;
        live?: boolean;
        auditLog?: boolean;
        i18n?: boolean;
        accessControl?: boolean;
```
could we remove "Provider" suffix?

2022-07-05 06:50 UTC, yildirayunlu commented on packages/core/src/interfaces/telementry.ts
> +        accessControlProvider?: boolean;
Encryption `object` does not support. We can do something like: 

```
  usesAuth?: boolean;
  usesAL?: boolean;
  usesLive?: boolean;
  usesRouter?: boolean;
  usesData?: boolean;
  usesI18n?: boolean;
  usesNotification?: boolean;
  usesAC?: boolean;
  version: string;
  resourceCount: number;
```

2022-07-06 14:37 UTC, omeraplak commented on packages/core/src/components/telemetry/index.tsx
> +            // https://telemetry.refine.dev/send
```suggestion
```

2022-07-06 15:39 UTC, omeraplak commented on .changeset/tame-windows-speak.md
> +
```suggestion
```

2022-07-07 11:34 UTC, drcivan requested changes

2022-07-07 11:34 UTC, drcivan commented on documentation/docs/guides-and-concepts/telemetry/telemetry.md
> +The tracking happens when a Refine application is loaded on users browser. On application init, a single HTTP request is sent to [https://telemery.refine.dev](https://telemery.refine.dev) . The reque
```suggestion
The tracking happens when a Refine application is loaded on users browser. On application init, a single HTTP request is sent to [https://telemery.refine.dev](https://telemery.refine.dev). The request body is encrypted with JSON Web Encryption (JWE) standard  ([ietf.org/doc/html/rfc7516](https://datatracker.ietf.org/doc/html/rfc7516)) to be decrypted securely on Refine servers.
```

2022-07-07 11:34 UTC, drcivan commented on .changeset/tame-windows-speak.md
> +You can check here for [details](https://refine.dev/docs/guides-and-concepts/telemetry/telemetry/).
```suggestion
Add a simple and transparent telemetry module to collect usage statistics defined within a very limited scope.

Tracking is completely safe and anonymous. It does not contain any personally identifiable Information and does not use cookies. Participation is optional and users can opt out easily.

You can check it here for [details](https://refine.dev/docs/guides-and-concepts/telemetry/telemetry/).
```

2022-07-07 11:34 UTC, drcivan commented on packages/core/src/components/telemetry/index.tsx
> +            });
we should define the PUBLIC_KEY as a const outside the function.

2022-07-07 14:57 UTC, yildirayunlu commented on packages/core/src/components/telemetry/index.tsx
> +            });
Since the `importJWK` method is async, I put it here. Maybe we can put it in utility folder.

2022-07-08 08:45 UTC, biskuvit requested changes

2022-07-08 08:45 UTC, biskuvit commented on .changeset/tame-windows-speak.md
> +Tracking is completely safe and anonymous. It does not contain any personally identifiable Information and does not use cookies. Participation is optional and users can opt out easily.
```suggestion
Tracking is completely safe and anonymous. It does not contain any personally identifiable information and does not use cookies. Participation is optional and users can opt-out easily.
```
also maybe we can use an entirely instead of a completely.

2022-07-08 08:45 UTC, biskuvit commented on .changeset/tame-windows-speak.md
> +You can check it here for [details](https://refine.dev/docs/guides-and-concepts/telemetry/telemetry/).
```suggestion
For more information, you can check the [documentation](https://refine.dev/docs/guides-and-concepts/telemetry/telemetry/).
```

2022-07-08 08:45 UTC, biskuvit commented on documentation/docs/guides-and-concepts/telemetry/telemetry.md
> +The tracking happens when a Refine application is loaded on users browser. On application init, a single HTTP request is sent to [https://telemery.refine.dev](https://telemery.refine.dev). The reques
```suggestion
The tracking happens when a Refine application is loaded on the user's browser. On application init, a single HTTP request is sent to [https://telemery.refine.dev](https://telemery.refine.dev). The request body is encrypted with JSON Web Encryption (JWE) standard  ([ietf.org/doc/html/rfc7516](https://datatracker.ietf.org/doc/html/rfc7516)) to be decrypted securely on Refine servers.
```

2022-07-08 08:45 UTC, biskuvit commented on documentation/docs/guides-and-concepts/telemetry/telemetry.md
> +There are no consequent requests on that session, as we do NOT collect any behavioral information as _page views_, _button clicks_ etc.
```suggestion
There are no consequent requests on that session, as we do NOT collect any behavioral information such as _page views_, _button clicks_, etc.
```

2022-07-08 08:45 UTC, biskuvit commented on documentation/docs/guides-and-concepts/telemetry/telemetry.md
> +You can opt out of telemetry by simply adding `disableTelemetry` prop to the `<Refine />` component.
```suggestion
You can opt-out of telemetry by simply adding `disableTelemetry` prop to the `<Refine />` component.
```

2022-07-08 09:39 UTC, omeraplak approved these changes

2022-07-08 09:40 UTC, omeraplak commented on packages/core/src/components/telemetry/index.tsx
> +        // TODO: Add temporary
let's not forget that @yildirayunlu @drcivan @aliemir

2022-07-13 07:15 UTC, aliemir commented on packages/core/src/components/telemetry/index.tsx
> +        console.log("--payload", JSON.stringify(payload, null, 2));
```suggestion
```

2022-07-13 08:24 UTC, aliemir approved these changes

2022-07-13 08:26 UTC, merged