docs(guide-and-concepts): save and continue guide and example
pankod/refine pull request #2089
Opened 2022-07-04 13:07 UTC by ozkalai

In this PR we have created the `save and continue` guide and an example.

2022-07-04 13:54 UTC, aliemir commented on documentation/docs/guides-and-concepts/save-and-continue.md
> +    const { formLoading, onFinish, redirect, id } = useForm({
```suggestion
    const { formLoading, onFinish, redirect } = useForm({
```

I think this is not necessary.

2022-07-04 13:57 UTC, aliemir commented on documentation/docs/guides-and-concepts/save-and-continue.md
> +        e: any,
```suggestion
        e: React.FormEventHandler<HTMLFormElement>,
```

Let's avoid using `any` here. To avoid any errors please add update the first line as 

```
import React, { useState } from "react";
```

2022-07-04 13:57 UTC, aliemir commented on documentation/docs/guides-and-concepts/save-and-continue.md
> +import { useState } from "react";
```suggestion
import React, { useState } from "react";
```

The update I mentioned below

2022-07-04 13:59 UTC, aliemir commented on examples/form/headless/saveAndContinue/src/pages/posts/create.tsx
> +import { useState } from "react";
```suggestion
import React, { useState } from "react";
```

same changes as the ones in the docs.

2022-07-04 14:00 UTC, aliemir commented on examples/form/headless/saveAndContinue/src/pages/posts/create.tsx
> +        e: any,
```suggestion
        e: React.FormEventHandler<HTMLFormElement>,
```

2022-07-04 14:01 UTC, aliemir commented on examples/form/headless/saveAndContinue/src/pages/posts/create.tsx
> +    const { formLoading, onFinish, redirect, id } = useForm({
```suggestion
    const { formLoading, onFinish, redirect } = useForm({
```

2022-07-04 14:03 UTC, aliemir commented on examples/form/headless/saveAndContinue/src/pages/posts/edit.tsx
> +import { useEffect, useState } from "react";
```suggestion
import React, { useEffect, useState } from "react";
```

same changes as the ones in the docs.

2022-07-04 14:03 UTC, aliemir commented on examples/form/headless/saveAndContinue/src/pages/posts/edit.tsx
> +    console.log(result);
```suggestion
```

2022-07-06 08:59 UTC, omeraplak requested changes

2022-07-06 08:59 UTC, omeraplak commented on .changeset/sweet-dragons-clean.md
> +redirect("edit", id)
```suggestion
const { redirect } = useForm();

redirect("edit", id);
```

2022-07-06 08:59 UTC, omeraplak commented on documentation/docs/guides-and-concepts/forms/save-and-continue.md
> +When we create our Create Page, we pass `redirect` false to the [`userForm`](/docs/core/hooks/useForm) hook that we will use to manage the form. Thus, we will be able to do the redirection we want in
```suggestion
When we create our Create Page, we pass `redirect` false to the [`useForm`](/docs/core/hooks/useForm) hook that we will use to manage the form. Thus, we will be able to do the redirection we want in our buttons.
```

2022-07-06 08:59 UTC, omeraplak commented on documentation/docs/guides-and-concepts/forms/save-and-continue.md
> +We will create the form and listen to the changes in this form with the help of a state.We add the `Save`, `Save and continue editing` and `Save and add another` buttons that we will use to submit th
```suggestion
We will create the form and listen to the changes in this form with the help of a state. We add the `Save`, `Save and continue editing`, and `Save and add another` buttons that we will use to submit the form to our page.
```

2022-07-06 08:59 UTC, omeraplak commented on documentation/docs/guides-and-concepts/forms/save-and-continue.md
> +`onFinish` function resolves respecting to the mutationMode property. In `pessimistic` mode it will resolve after the response is returned from the request, in `optimistic` and `undoable` modes it wi
```suggestion
`onFinish` function resolves respecting to the mutationMode property. In `pessimistic` mode it will resolve after the response is returned from the request, in `optimistic` and `undoable` modes it will resolve immediately. Only real await will happen in pessimistic mode and this will resolve with the response data, others will resolve immediately with undefined data.

[Refer to the `mutationMode` documentation for more details. &#8594](/guides-and-concepts/mutation-mode.md)
```

2022-07-06 14:20 UTC, omeraplak commented on documentation/docs/guides-and-concepts/forms/save-and-continue.md
> +    });
```suggestion
    const { tableQueryResult } = useTable<IPost>();
```

2022-07-06 14:22 UTC, omeraplak commented on documentation/docs/guides-and-concepts/forms/save-and-continue.md
> +### useForm without redirect
```suggestion
### Disable `useForm` redirection after successfull mutation
```

2022-07-06 15:46 UTC, aliemir approved these changes

2022-07-07 06:52 UTC, omeraplak approved these changes

2022-07-07 07:32 UTC, merged