feat: refine kbar command palette
pankod/refine pull request #2117
Opened 2022-07-07 12:09 UTC by biskuvit

Command palette feature added for the **refine**. We used [kbar](https://github.com/timc1/kbar) to generate the command palette.

2022-07-08 09:29 UTC, omeraplak commented on packages/kbar/test/jest.setup.ts
> +window.alert = jest.fn();
I guess we don't need these mocks?

2022-07-20 07:02 UTC, salihozdemir approved these changes

2022-07-21 05:05 UTC, aliemir commented on packages/kbar/src/hooks/useRefineKbar/index.tsx
> +                if (canDelete) {
Hard to read when `canDelete` is re-declared in it's own conditional scope 😅

2022-07-21 07:13 UTC, yildirayunlu approved these changes

2022-07-21 07:34 UTC, omeraplak requested changes

2022-07-21 07:34 UTC, omeraplak commented on packages/kbar/src/hooks/useRefineKbar/index.tsx
> +        const section = t(`${resourceName}.${resourceName}`, resourceName);
```suggestion
        const resourceName = label ?? name;
        const tempActions: Action[] = [];
        const section = t(`${resourceName}.${resourceName}`, resourceName);
```
We must handle `resource titles` like `useMenu` hook,
https://github.com/pankod/refine/blob/next/packages/core/src/hooks/menu/useMenu.tsx#L68

2022-07-21 10:05 UTC, ozkalai approved these changes

2022-07-21 11:15 UTC, omeraplak approved these changes

2022-07-21 11:34 UTC, omeraplak approved these changes

2022-07-21 11:34 UTC, merged