Disable telemetry on all examples.
pankod/refine pull request #2146
Opened 2022-07-18 07:24 UTC by yildirayunlu

We turn off telemetry in the examples to get telemetry data more accurately.

2022-07-18 07:59 UTC, omeraplak requested changes

2022-07-18 07:59 UTC, omeraplak commented on examples/accessControl/casbin/src/App.tsx
> +            disableLayout={true}
```suggestion
            disableTelemetry={true}
```

2022-07-18 11:29 UTC, biskuvit approved these changes

2022-07-18 11:53 UTC, aliemir approved these changes

2022-07-19 06:31 UTC, omeraplak approved these changes

2022-07-19 06:37 UTC, merged