feat(useCustomMutation): Add useCustomMutation hook
pankod/refine pull request #2229
Opened 2022-07-27 11:14 UTC by yildirayunlu

Added useCustomMutationHook for easier mutation.

2022-07-27 12:35 UTC, omeraplak commented on .changeset/silent-crabs-push.md
> +Added useCustomMutation for custom mutation.
```suggestion
Added `useCustomMutation`hook for custom mutation requests.
```

2022-07-27 12:35 UTC, omeraplak commented on .changeset/silent-crabs-push.md
> +const { mutation } = useCustomMutation();
```suggestion
import { useCustomMutation } from "@pankod/refine-core";
const { mutation } = useCustomMutation();
```

2022-07-27 12:35 UTC, omeraplak commented on documentation/docs/core/hooks/data/useCustom.md
> +If you need to use 'useCustom' for mutation operations, use the [useCustomMutation](/core/hooks/data/useCustomMutation.md) hook.
```suggestion
if you need to custom mutation request, use the [useCustomMutation](/core/hooks/data/useCustomMutation.md) hook.
```

2022-07-27 12:56 UTC, ozkalai approved these changes

2022-07-27 14:14 UTC, omeraplak approved these changes

2022-07-27 14:33 UTC, salihozdemir approved these changes

2022-07-27 15:17 UTC, omeraplak requested changes

2022-07-27 15:17 UTC, omeraplak commented on documentation/docs/core/hooks/data/useCustomMutation.md
> +-   You can send a request to any link, using any of the methods (`post, put, patch`).
```suggestion
-   You can send a request to any link, using any of the methods (`post, put, patch, delete`).
```

2022-07-27 15:17 UTC, omeraplak commented on documentation/docs/core/hooks/data/useCustomMutation.md
> +| method <div className="required">Required</div> | Method                                                                                             | `post`, `put`, `patch`
```suggestion
| method <div className="required">Required</div> | Method                                                                                             | `post`, `put`, `patch`, `delete`                                                     |
```

2022-07-28 06:44 UTC, omeraplak approved these changes

2022-07-28 06:44 UTC, merged