Feat/auth page
pankod/refine pull request #2299
Opened 2022-08-08 19:35 UTC by biskuvit

Added auth page for common authentication forms.

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2022-08-16 14:37 UTC, omeraplak commented on packages/react-router-v6/src/routeProvider.tsx
> +                    AuthPage ? (
Can we convert this logic to function? Looks like we'll have to do the same on all routers

2022-08-19 06:45 UTC, yildirayunlu commented on packages/core/src/components/pages/auth/components/login/index.tsx
> +            } else return link;
```suggestion
            if (typeof link === "string") {
                return <Link to={link}>{text}</Link>;
            }
            return link;
```

2022-08-19 06:45 UTC, yildirayunlu commented on packages/core/src/components/pages/auth/components/register/index.tsx
> +                    )}
should be in the `<label>` tag.

2022-08-19 06:45 UTC, yildirayunlu commented on packages/core/src/components/pages/auth/components/resetPassword/index.tsx
> +            } else return link;
```suggestion
            if (typeof link === "string") {
                return <Link to={link}>{text}</Link>;
            } 
            return link;
```

2022-08-19 06:45 UTC, yildirayunlu commented on packages/core/src/components/pages/auth/components/updatePassword/index.tsx
> +                    )}
should be in the `<label>` tag.

2022-08-19 06:45 UTC, yildirayunlu commented on packages/core/src/components/pages/auth/components/updatePassword/index.tsx
> +                    {translate(
should be in the `<label>` tag.

2022-08-19 11:47 UTC, omeraplak approved these changes

2022-08-22 06:49 UTC, omeraplak approved these changes

2022-08-22 06:49 UTC, yildirayunlu approved these changes

2022-08-22 10:52 UTC, omeraplak approved these changes

2022-08-22 10:52 UTC, omeraplak commented on packages/core/src/hooks/auth/useLogin/index.ts
> +    const { to } = qs.parse(search, {
🚀

2022-08-22 14:26 UTC, omeraplak requested changes

2022-08-22 14:26 UTC, omeraplak commented on .changeset/real-planes-float.md
> +📌 Added `useUpdatePassword` hook. This hook is used to update password. `userUpdatePassword` falls into `updatePassword` function of [`AuthProvider`](https://refine.dev/docs/core/providers/auth-provi
```suggestion
📌 Added `useUpdatePassword` hook. This hook is used to update password. `useUpdatePassword` falls into `updatePassword` function of [`AuthProvider`](https://refine.dev/docs/core/providers/auth-provider/).
```

2022-08-22 14:26 UTC, omeraplak commented on examples/fineFoods/admin/antd/src/pages/dashboard/index.tsx
> +                    {/* <DeliveryMap /> */}
```suggestion
                    <DeliveryMap />
```

2022-08-22 14:26 UTC, omeraplak commented on packages/core/src/components/pages/auth/components/login/index.tsx
> +                                password,
Do we need email and password in the provider login?

2022-08-22 14:26 UTC, omeraplak commented on packages/core/src/components/pages/auth/components/register/index.tsx
> +                    ) : (
How exactly is this used?

2022-08-22 14:26 UTC, omeraplak commented on packages/core/src/components/pages/auth/components/login/index.tsx
> +                    ) : (
How exactly is this used?

2022-08-23 07:30 UTC, salihozdemir commented on examples/authentication/headless/index.html
> +        <title>refine headless authenticationexample</title>
```suggestion
        <title>refine headless authentication example</title>
```

2022-08-23 07:42 UTC, salihozdemir approved these changes

2022-08-23 07:42 UTC, salihozdemir commented on packages/core/src/components/containers/refine/index.tsx
> +    /** @deprecated Login page to AuthPage */
```suggestion
    /** @deprecated LoginPage deprecated. Use AuthPage instead. */
```

2022-08-23 07:50 UTC, ozkalai commented on examples/authentication/headless/src/pages/posts/create.tsx
> +import { useForm, useSelect } from "@pankod/refine-antd";
imports can be merge

2022-08-23 07:50 UTC, ozkalai commented on packages/core/src/components/pages/auth/components/resetPassword/index.tsx
> +import { useTranslate, useRouterContext, useResetPassword } from "@hooks";
import order can be arrange

2022-08-23 07:50 UTC, ozkalai commented on examples/authentication/headless/src/pages/posts/create.tsx
> +import { useForm, useSelect } from "@pankod/refine-antd";
antd elements should removed from headless examples

2022-08-23 07:50 UTC, ozkalai commented on examples/authentication/headless/src/pages/posts/edit.tsx
> +import { useForm, useSelect } from "@pankod/refine-antd";
antd elements should remove from headless examples

2022-08-23 07:50 UTC, ozkalai commented on examples/authentication/headless/src/pages/posts/list.tsx
> +import {
antd elements should remove from headless example

2022-08-23 07:50 UTC, ozkalai commented on examples/authentication/headless/src/pages/posts/show.tsx
> +import { Show, Typography, MarkdownField } from "@pankod/refine-antd";
antd elements should remove from headless example

2022-08-23 07:50 UTC, ozkalai commented on packages/core/src/components/pages/auth/components/updatePassword/index.tsx
> +    const [newpPassword, setNewPassword] = useState("");
```suggestion
    const [newPassword, setNewPassword] = useState("");
```
I am not sure the name of state but it has typo

2022-08-23 07:50 UTC, ozkalai commented on packages/core/src/components/pages/auth/index.tsx
> +export interface ILoginForm {
Should login form entries be optional or mandatory, especially passwords?

2022-08-24 09:26 UTC, omeraplak approved these changes

2022-09-01 12:41 UTC, merged