docs: add mantine basic view docs
pankod/refine pull request #2718
Opened 2022-10-11 15:09 UTC by salihozdemir

## TODO
- [x] Added Create View
- [x] Added Edit View
- [x] Added List View
- [x] Added Show View

## Known Isssues
- [x] Propstable Edit View
- [x] Propstable List View
- [x] Propstable Show View
- [x] Add LoadingOverlay
- [x] Fix `goBack`
- [x] List View first live example has a error fix it
- [x] Antd Show first live example not working

<hr />

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2022-10-11 15:17 UTC, omeraplak approved these changes

2022-10-12 07:21 UTC, omeraplak commented on documentation/docs/api-reference/mantine/components/basic-views/create.md
> +        <Create resource="posts">
```suggestion
        <Create resource="custom resource">
```

2022-10-12 07:21 UTC, omeraplak commented on documentation/docs/api-reference/mantine/components/basic-views/create.md
> +        <Create goBack="😊">
In the ant design example, the "back" button works. What difference is there?

https://6346611b9090ba29d8782994--refine-doc-preview.netlify.app/docs/api-reference/antd/components/basic-views/create/#goback

2022-10-12 07:21 UTC, omeraplak commented on documentation/docs/api-reference/mantine/components/basic-views/create.md
> +To toggle the loading state of the `<Create/>` component, you can use the `isLoading` property.
Could we use LoadingOverlay?
https://mantine.dev/core/loading-overlay/

2022-10-12 07:50 UTC, salihozdemir commented on documentation/docs/api-reference/mantine/components/basic-views/create.md
> +        <Create resource="posts">
I think, it is not problem because the example within the custom page.

2022-10-12 07:55 UTC, salihozdemir commented on documentation/docs/api-reference/mantine/components/basic-views/create.md
> +        <Create goBack="😊">
Yes, I noticed it. The difference is mantine expects a whole Button group, antd expects only icon for the BackButton. MUI logis is the same with Mantine. We should fix it both.

2022-10-12 07:57 UTC, salihozdemir commented on documentation/docs/api-reference/mantine/components/basic-views/create.md
> +To toggle the loading state of the `<Create/>` component, you can use the `isLoading` property.
I'll add it after I finish the docs. 👍

2022-10-13 06:37 UTC, omeraplak requested changes

2022-10-13 06:37 UTC, omeraplak commented on packages/ui-types/src/types/crud.tsx
> +     */
```suggestion
    /**
     * Adds a `<DeleteButton />`
     * @default If the resource has `canDelete` prop it is `true` else `false`
     */
     canDelete?: boolean;
```

2022-10-13 09:08 UTC, omeraplak approved these changes

2022-10-13 11:12 UTC, merged