fix(auth-model): changes made for model to be responsive in store
pankod/refine pull request #2801
Opened 2022-10-17 15:40 UTC by s-vamshi

Made necessary changes to make auth model responsive
This is how it looks now - 
![image](https://user-images.githubusercontent.com/62489114/196221530-27051bec-4f17-476a-8823-5a1e3aae0087.png)

### Closing issues

closes #2797 

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2022-10-17 15:40 UTC, s-vamshi commented
@omeraplak can you please review this PR when you are free?

2022-10-17 18:47 UTC, aliemir commented on examples/store/src/components/ui/Modal/Modal.module.css
> +  @apply fixed bg-black bg-opacity-40 grid overflow-y-scroll flex items-center inset-0 z-50 justify-center;
isn't `grid` and `flex` classes conflict with each other? @s-vamshi

2022-10-18 01:02 UTC, s-vamshi commented on examples/store/src/components/ui/Modal/Modal.module.css
> +  @apply fixed bg-black bg-opacity-40 grid overflow-y-scroll flex items-center inset-0 z-50 justify-center;
Yes they will conflict and i have removed it. Can you please check?

2022-10-18 06:39 UTC, s-vamshi commented
@omeraplak can you please review my PR?

2022-10-18 06:58 UTC, omeraplak commented on examples/store/src/components/ui/Modal/Modal.module.css
> +  @apply rounded bg-primary border border-accent-2 relative;
```suggestion
  @apply bg-primary border border-accent-2 relative;
```

2022-10-18 07:24 UTC, s-vamshi commented
@omeraplak committed changes which you have suggested.

2022-10-18 07:51 UTC, salihozdemir requested changes
Hey @s-vamshi,
You catch a good point!, But your changes change out design, so i reviewed and changed the code please check it out. 🙏🏻

2022-10-18 07:51 UTC, salihozdemir commented on examples/store/src/components/ui/Modal/Modal.module.css
> +  @apply fixed bg-black bg-opacity-40 grid overflow-y-scroll items-center inset-0 z-50 justify-center;
```suggestion
  @apply fixed bg-black bg-opacity-40 flex overflow-y-scroll items-center inset-0 z-50 justify-center;
```

2022-10-18 07:51 UTC, salihozdemir commented on examples/store/src/components/ui/Modal/Modal.module.css
> +  @apply bg-primary border border-accent-2 relative;
```suggestion
  @apply bg-primary border border-accent-2 relative p-2 md:p-12;
```

2022-10-18 07:51 UTC, salihozdemir commented on examples/store/src/components/ui/Modal/Modal.module.css
> +  @apply hover:text-accent-5 transition ease-in-out duration-150 focus:outline-none absolute right-0 top-0 m-4;
```suggestion
  @apply hover:text-accent-5 transition ease-in-out duration-150 focus:outline-none absolute right-0 top-0 m-6;
```

2022-10-18 08:14 UTC, s-vamshi commented on examples/store/src/components/ui/Modal/Modal.module.css
> +  @apply fixed bg-black bg-opacity-40 grid overflow-y-scroll items-center inset-0 z-50 justify-center;
@salihozdemir if we go with flex class the problem still exists.
In desktop view, close button is only visible half if we use flex.
And in mobile view, This is how it looks
Even though scroll bar is at the top, model's top portion is not visible.
![image](https://user-images.githubusercontent.com/62489114/196374368-d6281145-54c2-4410-a126-5cb0e76ea0f8.png)

2022-10-18 08:19 UTC, salihozdemir commented on examples/store/src/components/ui/Modal/Modal.module.css
> +  @apply fixed bg-black bg-opacity-40 grid overflow-y-scroll items-center inset-0 z-50 justify-center;
@s-vamshi, You are right! 🚀 I missed it!

2022-10-18 08:20 UTC, salihozdemir approved these changes

2022-10-18 08:21 UTC, s-vamshi commented on examples/store/src/components/ui/Modal/Modal.module.css
> +  @apply fixed bg-black bg-opacity-40 grid overflow-y-scroll items-center inset-0 z-50 justify-center;
That's the reason i have gone with grid.

2022-10-18 08:27 UTC, aliemir approved these changes

2022-10-18 09:00 UTC, merged